name: Go App CI/CD

on:
  push:
    branches:
      - main
    tags:
      - '*'  # Запуск при добавлении любого тега
  pull_request:
    branches:
      - main  # Тесты при PR в ветку main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.26.x'

      - name: Install dependencies
        run: go mod download

      - name: Lint & format check
        run: |
          go fmt ./...
          go vet ./...

      - name: Run tests (including parcel_test.go)
        run: go test -v ./...  # parcel_test.go будет автоматически включён
       

  publish-to-dockerhub:
    needs: test-and-lint  # Зависит от успешного завершения тестов
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')   # Выполняется только при наличии тега
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Секретный ключ DOCKER_USERNAME
          password: ${{ secrets.DOCKER_PASSWORD }}  # Секретный ключ DOCKER_PASSWORD
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: kholevitskayaanna/12-sprint-final
      
      - name: Build and push Docker image
        id: buildx
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          repository: kholevitskayaanna/12-sprint-final  # Docker ID + имя репозитория
          # tags: v8.0 # ${{ github.ref_name }}  # Используем имя тега из GitHub
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Debug Image Name  # <-- Вставляем этот шаг
        run: |
          echo "Pushing image: ${{ steps.buildx.outputs.fullyQualifiedImage }}"  

      - name: Print success message
        run: |
          echo "Docker image published: kholevitskayaanna/12-sprint-final"
          echo "Tag: ${{ github.ref_name }}"